
language: r
sudo: required
dist: xenial

jobs:
  include:
  - r: devel
  - r: release
  - r: oldrel

addons:
  apt:
    packages:
     - libgdal-dev
     - libproj-dev 
     - libgeos-dev
     - libudunits2-dev 

warnings_are_errors: true

r_packages:
  - devtools
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
