language: r
sudo: required
dist: xenial

jobs:
  include:
  - r: devel
  - r: release
  - r: oldrel


addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

warnings_are_errors: true

r_packages:
  - devtools
  - sp
  - rgdal
  - roxygen2
  - rmarkdown
